channel: '#sra-builds'
workflows:
  build:
    when:
      event: push
    pipeline:
      test:
        image: hub-eu.terra.songsterr.com/builderr-android
        commands:
          - ./gradlew --console=plain testDebug --stacktrace
        artifacts:
          - androidsvg/build/reports/tests
        message: |
          <${BUILDERR_ARTIFACTS_LINK}/tests/testDebugUnitTest|Unit test report>
      publish:
        image: hub-eu.terra.songsterr.com/builderr-android
        commands:
          - ./gradlew publish --stacktrace
