pipeline:
  test:
    image: hub.terra.songsterr.com/builderr-android
    commands:
      - ./gradlew --console=plain testDebug --stacktrace
    artifacts:
      - androidsvg/build/reports/tests
    message: |
      <${BUILDERR_ARTIFACTS_LINK}/tests/testDebugUnitTest|Unit test report>
  publish:
    image: hub.terra.songsterr.com/builderr-android
    commands:
      - ./gradlew publish --stacktrace
